### PR TITLE
missing comma in example script

### PR DESCRIPTION
**Pull request by changhoonhahn**

### CODE REVIEW

**Comment by QuiteAFoxtrot** [comment]
Straightforward, one comma change

**Review by QuiteAFoxtrot — APPROVED** [review]
one comma change, approving

**Comment by QuiteAFoxtrot** [comment]
Don't know why the checks aren't passing here on 3.8 and 3.9:
python/vast/test/test_V2.py ........                                     [ 42%]
python/vast/test/test_V2_util.py .......                                 [ 78%]
Fatal Python error: Segmentation fault

**Comment by kadglass** [comment]
Failing checks for 3.8 and 3.9 are fixed in a different pull request, so approving this.

**Pull request merged**
